### ISSUE TITLE
Milestone4 Activities checklist 

### ISSUE THREAD

**Issue by shivajena** [UBC-MDS/doggodash-R#5]
- [ ] README/Description - including heroku link as per instructions
- [ ] back end plots
- [ ] front end dash codes
- [ ] Heroku deployment
